### ISSUE TITLE
Using variable 'Units_Sold' before assignment

### ISSUE THREAD

**Issue by AIatMyCommand** [AIatMyCommand/Inventory_Profitability_Analyzer#1]
On Menu Add Items: Using variable 'Units_Sold' before assignment [E:used-before-assignment]	Product_Line_Analyzer	line 368

**Comment by DataWearsAHood** [comment]
Update error message - no `Units_sold`: https://github.com/AIatMyCommand/Inventory_Profitability_Analyzer/blob/17f47b318c1877f8ae262216bdc487434b7416a8/Inventory_Profitability_Analyzer/Product_Line_Analyzer.py#L368
