### ISSUE TITLE
Browse & search

### ISSUE THREAD

**Issue by AIatMyCommand** [AIatMyCommand/Inventory_Profitability_Analyzer#10]
Each screen doesn't show the proper table

**Comment by DataWearsAHood** [comment]
`Browse` MVP: start with displaying the first 10 items in the DB, using a `LIMIT 10` clause in your SQL query.

**Comment by AIatMyCommand** [comment]
I realized the cause of this error the table is drawn with a loop & the loop iterates over the number of entries. All 4/5 problems may be caused by the fact that I'm having trouble adding items to the DB. I will have to check if there is a proper connection as I made a connection in a function & assumed that it would persist

**Comment by DataWearsAHood** [comment]
If you create a function to add a hard-coded item to the DB - does that work?
Once that does, make the input fields variable.
Last step is to hook that fn into your UI
