### ISSUE TITLE
Instance of 'float' has no 'delete' member

### ISSUE THREAD

**Issue by AIatMyCommand** [AIatMyCommand/Inventory_Profitability_Analyzer#2]
On menu Add Items: Instance of 'float' has no 'delete' member	line 395

**Comment by DataWearsAHood** [comment]
Create & place `Entry` object
> 339: Cost_to_Ship = Entry(Add_Items_Screen)
> 342: Cost_to_Ship.grid(row=4, column=2)

Overwrite `Entry` object with a `float` scalar
> 378: Cost_to_Ship = float(Ending_INV.get())

Error trying to `.delete()` a `float`
> 395: Cost_to_Ship.delete(0, END)
