### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by AIatMyCommand** [AIatMyCommand/Inventory_Profitability_Analyzer#4]
In menu Add_Items menu upon clicking submit button I trigger except on line 276: An error occurred -  near "blossom": syntax error <--If I put a space in the description
An error occurred -  near "16.45": syntax error <-- If I enter a decimal
An error occurred -  near "16.0": syntax error <-- If I put no spaces & only whole numbers
but the asseretions are never triggered so I know that they convert properly to floats & int & strings

**Comment by DataWearsAHood** [comment]
Probably the SQL query on this line: https://github.com/AIatMyCommand/Inventory_Profitability_Analyzer/blob/17f47b318c1877f8ae262216bdc487434b7416a8/Inventory_Profitability_Analyzer/Product_Line_Analyzer.py#L385

Where does `ADD TABLE ...` come from?
I think you meant to: https://www.sqlitetutorial.net/sqlite-insert/
