### ISSUE TITLE
'sqlite3' has no 'connect' member

### ISSUE THREAD

**Issue by AIatMyCommand** [AIatMyCommand/Inventory_Profitability_Analyzer#8]
SError from pylint: Module 'sqlite3' has no 'connect' member [E:no-member]	Product_Line_Analyzer	C:\Users\nicho\Documents\GitHub\Product_Line_Analyzer\Inventory_Profitability_Analyzer\Product_Line_Analyzer.py	Line 220

**Comment by DataWearsAHood** [comment]
weird... you can try using `from sqlite3 import connect as sqlite3_connect` instead - then use the FN like: `sqlite3_connect(db_name)`
