### ISSUE TITLE
'sqlite3' has no 'Error' member 

### ISSUE THREAD

**Issue by AIatMyCommand** [AIatMyCommand/Inventory_Profitability_Analyzer#9]
'sqlite3' has no 'Error' member [E:no-member]	Product_Line_Analyzer	C:\Users\nicho\Documents\GitHub\Product_Line_Analyzer\Inventory_Profitability_Analyzer\Product_Line_Analyzer.py	Line 227

**Comment by DataWearsAHood** [comment]
since you have this error twice, there may be something wrong with your import... 🤔
